// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		double a;
		int greater = 0;
		int lessOrEqual = 0;
		while (n>0){
			a=Math.random();
			if (a>0.5){
				greater++;
			}
			else {
				lessOrEqual++;
			}
			n--;
		}
		if (greater == 0 || lessOrEqual == 0){
			System.out.println("> 0.5:  " + greater + " times");
			System.out.println("<= 0.5:  " + lessOrEqual + " times");
		}
		else if (greater > lessOrEqual){
			System.out.println("> 0.5:  " + greater + " times");
			System.out.println("<= 0.5: " + lessOrEqual + " times");
			System.out.println("Ratio  "+(double) lessOrEqual/greater);
		}
		else {
			System.out.println("> 0.5:  " + greater + " times");
			System.out.println("<= 0.5:  " + lessOrEqual + " times");
			System.out.println("Ratio  " + (double) greater/ lessOrEqual);

		}
	}
}
